/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as NewsMediaRouteImport } from './routes/news-media'
import { Route as ParaPickleballRouteImport } from './routes/para-pickleball'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsMediaRoute = NewsMediaRouteImport.update({
  id: '/news-media',
  path: '/news-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaPickleballRoute = ParaPickleballRouteImport.update({
  id: '/para-pickleball',
  path: '/para-pickleball',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/athletes': typeof AthletesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news-media': typeof NewsMediaRoute
  '/para-pickleball': typeof ParaPickleballRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/athletes': typeof AthletesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news-media': typeof NewsMediaRoute
  '/para-pickleball': typeof ParaPickleballRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/athletes': typeof AthletesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news-media': typeof NewsMediaRoute
  '/para-pickleball': typeof ParaPickleballRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/athletes'
    | '/contact'
    | '/events'
    | '/news-media'
    | '/para-pickleball'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/athletes'
    | '/contact'
    | '/events'
    | '/news-media'
    | '/para-pickleball'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/athletes'
    | '/contact'
    | '/events'
    | '/news-media'
    | '/para-pickleball'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AthletesRoute: typeof AthletesRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  NewsMediaRoute: typeof NewsMediaRoute
  ParaPickleballRoute: typeof ParaPickleballRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-media': {
      id: '/news-media'
      path: '/news-media'
      fullPath: '/news-media'
      preLoaderRoute: typeof NewsMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-pickleball': {
      id: '/para-pickleball'
      path: '/para-pickleball'
      fullPath: '/para-pickleball'
      preLoaderRoute: typeof ParaPickleballRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AthletesRoute: AthletesRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  NewsMediaRoute: NewsMediaRoute,
  ParaPickleballRoute: ParaPickleballRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
